// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pagent.proto

package proto_people_agent // import "github.com/synerex/proto_people_agent"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Agent Message (mainly for supply)
type PAgent struct {
	Id                   int32     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Point                []float64 `protobuf:"fixed64,2,rep,packed,name=point,proto3" json:"point,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PAgent) Reset()         { *m = PAgent{} }
func (m *PAgent) String() string { return proto.CompactTextString(m) }
func (*PAgent) ProtoMessage()    {}
func (*PAgent) Descriptor() ([]byte, []int) {
	return fileDescriptor_pagent_cd1a404f55f65b81, []int{0}
}
func (m *PAgent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PAgent.Unmarshal(m, b)
}
func (m *PAgent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PAgent.Marshal(b, m, deterministic)
}
func (dst *PAgent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PAgent.Merge(dst, src)
}
func (m *PAgent) XXX_Size() int {
	return xxx_messageInfo_PAgent.Size(m)
}
func (m *PAgent) XXX_DiscardUnknown() {
	xxx_messageInfo_PAgent.DiscardUnknown(m)
}

var xxx_messageInfo_PAgent proto.InternalMessageInfo

func (m *PAgent) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PAgent) GetPoint() []float64 {
	if m != nil {
		return m.Point
	}
	return nil
}

type PAgents struct {
	Agents               []*PAgent `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PAgents) Reset()         { *m = PAgents{} }
func (m *PAgents) String() string { return proto.CompactTextString(m) }
func (*PAgents) ProtoMessage()    {}
func (*PAgents) Descriptor() ([]byte, []int) {
	return fileDescriptor_pagent_cd1a404f55f65b81, []int{1}
}
func (m *PAgents) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PAgents.Unmarshal(m, b)
}
func (m *PAgents) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PAgents.Marshal(b, m, deterministic)
}
func (dst *PAgents) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PAgents.Merge(dst, src)
}
func (m *PAgents) XXX_Size() int {
	return xxx_messageInfo_PAgents.Size(m)
}
func (m *PAgents) XXX_DiscardUnknown() {
	xxx_messageInfo_PAgents.DiscardUnknown(m)
}

var xxx_messageInfo_PAgents proto.InternalMessageInfo

func (m *PAgents) GetAgents() []*PAgent {
	if m != nil {
		return m.Agents
	}
	return nil
}

func init() {
	proto.RegisterType((*PAgent)(nil), "pagent.PAgent")
	proto.RegisterType((*PAgents)(nil), "pagent.PAgents")
}

func init() { proto.RegisterFile("pagent.proto", fileDescriptor_pagent_cd1a404f55f65b81) }

var fileDescriptor_pagent_cd1a404f55f65b81 = []byte{
	// 154 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x48, 0x4c, 0x4f,
	0xcd, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0x94, 0xf4, 0xb8, 0xd8,
	0x02, 0x1c, 0x41, 0x2c, 0x21, 0x3e, 0x2e, 0xa6, 0xcc, 0x14, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xd6,
	0x20, 0xa6, 0xcc, 0x14, 0x21, 0x11, 0x2e, 0xd6, 0x82, 0xfc, 0xcc, 0xbc, 0x12, 0x09, 0x26, 0x05,
	0x66, 0x0d, 0xc6, 0x20, 0x08, 0x47, 0xc9, 0x90, 0x8b, 0x1d, 0xa2, 0xbe, 0x58, 0x48, 0x8d, 0x8b,
	0x0d, 0x6c, 0x46, 0xb1, 0x04, 0xa3, 0x02, 0xb3, 0x06, 0xb7, 0x11, 0x9f, 0x1e, 0xd4, 0x06, 0x88,
	0x82, 0x20, 0xa8, 0xac, 0x93, 0x7a, 0x94, 0x6a, 0x7a, 0x66, 0x49, 0x46, 0x69, 0x92, 0x5e, 0x72,
	0x7e, 0xae, 0x7e, 0x71, 0x65, 0x5e, 0x6a, 0x51, 0x6a, 0x85, 0x3e, 0xd8, 0x19, 0xf1, 0x05, 0xa9,
	0xf9, 0x05, 0x39, 0xa9, 0xf1, 0x60, 0x95, 0x49, 0x6c, 0x60, 0x31, 0x63, 0x40, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xb6, 0xf1, 0xa1, 0x26, 0xaa, 0x00, 0x00, 0x00,
}
